

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findgodot-cpp.cmake")
# Global approach
set(godot-cpp_FOUND 1)
set(godot-cpp_VERSION "3.3")

find_package_handle_standard_args(godot-cpp REQUIRED_VARS
                                  godot-cpp_VERSION VERSION_VAR godot-cpp_VERSION)
mark_as_advanced(godot-cpp_FOUND godot-cpp_VERSION)


set(godot-cpp_INCLUDE_DIRS "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/include")
set(godot-cpp_INCLUDE_DIR "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/include")
set(godot-cpp_INCLUDES "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/include")
set(godot-cpp_RES_DIRS )
set(godot-cpp_DEFINITIONS )
set(godot-cpp_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(godot-cpp_COMPILE_DEFINITIONS )
set(godot-cpp_COMPILE_OPTIONS_LIST "" "")
set(godot-cpp_COMPILE_OPTIONS_C "")
set(godot-cpp_COMPILE_OPTIONS_CXX "")
set(godot-cpp_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(godot-cpp_LIBRARIES "") # Will be filled later
set(godot-cpp_LIBS "") # Same as godot-cpp_LIBRARIES
set(godot-cpp_SYSTEM_LIBS )
set(godot-cpp_FRAMEWORK_DIRS )
set(godot-cpp_FRAMEWORKS )
set(godot-cpp_FRAMEWORKS_FOUND "") # Will be filled later
set(godot-cpp_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(godot-cpp_FRAMEWORKS_FOUND "${godot-cpp_FRAMEWORKS}" "${godot-cpp_FRAMEWORK_DIRS}")

mark_as_advanced(godot-cpp_INCLUDE_DIRS
                 godot-cpp_INCLUDE_DIR
                 godot-cpp_INCLUDES
                 godot-cpp_DEFINITIONS
                 godot-cpp_LINKER_FLAGS_LIST
                 godot-cpp_COMPILE_DEFINITIONS
                 godot-cpp_COMPILE_OPTIONS_LIST
                 godot-cpp_LIBRARIES
                 godot-cpp_LIBS
                 godot-cpp_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to godot-cpp_LIBS and godot-cpp_LIBRARY_LIST
set(godot-cpp_LIBRARY_LIST godot-cpp.windows.debug.64)
set(godot-cpp_LIB_DIRS "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_godot-cpp_DEPENDENCIES "${godot-cpp_FRAMEWORKS_FOUND} ${godot-cpp_SYSTEM_LIBS} ")

conan_package_library_targets("${godot-cpp_LIBRARY_LIST}"  # libraries
                              "${godot-cpp_LIB_DIRS}"      # package_libdir
                              "${_godot-cpp_DEPENDENCIES}"  # deps
                              godot-cpp_LIBRARIES            # out_libraries
                              godot-cpp_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "godot-cpp")                                      # package_name

set(godot-cpp_LIBS ${godot-cpp_LIBRARIES})

foreach(_FRAMEWORK ${godot-cpp_FRAMEWORKS_FOUND})
    list(APPEND godot-cpp_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND godot-cpp_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${godot-cpp_SYSTEM_LIBS})
    list(APPEND godot-cpp_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND godot-cpp_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(godot-cpp_LIBRARIES_TARGETS "${godot-cpp_LIBRARIES_TARGETS};")
set(godot-cpp_LIBRARIES "${godot-cpp_LIBRARIES};")

set(CMAKE_MODULE_PATH "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/dns/.conan/data/godot-cpp/3.3/local/stable/package/164640aad040835ac89882393a96d89200694f04/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET godot-cpp::godot-cpp)
        add_library(godot-cpp::godot-cpp INTERFACE IMPORTED)
        if(godot-cpp_INCLUDE_DIRS)
            set_target_properties(godot-cpp::godot-cpp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${godot-cpp_INCLUDE_DIRS}")
        endif()
        set_property(TARGET godot-cpp::godot-cpp PROPERTY INTERFACE_LINK_LIBRARIES
                     "${godot-cpp_LIBRARIES_TARGETS};${godot-cpp_LINKER_FLAGS_LIST}")
        set_property(TARGET godot-cpp::godot-cpp PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${godot-cpp_COMPILE_DEFINITIONS})
        set_property(TARGET godot-cpp::godot-cpp PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${godot-cpp_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${godot-cpp_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
